services:
    web:
        build: .
        image: todo-app:dev
        ports: 
            - "5000:5000"
        env_file: .env
        volumes:
            - type: bind
              source: todo_app
              target: /opt/todoapp/todo_app

