services:
    dev:
        build:
            context: .
            target: dev
        image: todo-app:dev
        container_name: todo-app.dev
        ports: 
            - "5000:5000"
        env_file: .env
        volumes:
            - type: bind
              source: todo_app
              target: /opt/todoapp/todo_app

    prod:
        build: 
            context: .
            target: prod
        image: todo-app:prod
        container_name: todo-app.prod
        ports: 
            - "8000:8000"
        env_file: .env

    test:
        build:
            context: .
            target: test
        image: todo-app:test
        container_name: todo-app.test
        env_file: .env
        volumes:
            - type: bind
              source: todo_app
              target: /opt/todoapp/todo_app
            - type: bind
              source: tests
              target: /opt/todoapp/tests


    ci:
        build:
            context: .
            target: ci
        image: todo-app:ci
        container_name: todo-app.ci
        env_file: .env

