- name: First Playbook
  hosts: module4
  tasks:
  - name: Install git
    ansible.builtin.yum:
      name: git
      state: latest
    become: true  

  - name: Install python 3.x
    ansible.builtin.yum:
      name: python
      state: latest
    become: true  

  # install poetry TODDDO
  # create /opt/todoapp TODO
  # clone the app TODO
  # install project dependencies TODO
  # create a .env file TODO
  # update the .env file to jinja TODO
  # maybe use ansible vault TODO
  # set the app as a service in syssctl TODO
  #
