- name: First Playbook
  hosts: module4
  tasks:
  - name: Ping the hosts
    ansible.builtin.ping:
  - name: Print message
    ansible.builtin.debug:
      msg: Hello, ansible!
  # install git TODO
  # Install python3 TODO
  # install poetry TODDDO
  # create /opt/todoapp TODO
  # clone the app TODO
  # install project dependencies TODO
  # create a .env file TODO
  # update the .env file to jinja TODO
  # maybe use ansible vault TODO
  # set the app as a service in syssctl TODO
  #
