- name: Install TODO app in module4 servers
  hosts: module4
  tasks:
  - name: Install git
    ansible.builtin.yum:
      name: git
      state: latest
    become: true  

  - name: Install python 3.x
    ansible.builtin.yum:
      name: python3
      state: latest
    become: true  
  
  # create /opt/todoapp TODO
  # make the folder read/writeable by ec2-user
  - name: mkdir and chown
    ansible.builtin.file: 
      path: /opt/todoapp
      state: directory
      owner: ec2-user
    become: true

  # retrieve the app TODO
  - name: clone TODO app into service
    ansible.builtin.git:
      repo: https://github.com/sweavo/devops-course-starter.git
      dest: /opt/todoapp
      single_branch: yes
      version: release/prep
      depth: 1
      force: true
    become: true


  # install poetry TODDDO
  # install project dependencies TODO
  # create a .env file TODO
  # update the .env file to jinja TODO
  # maybe use ansible vault TODO
  # set the app as a service in syssctl TODO
  #
