- name: Install TODO app in module4 servers
  hosts: module4
  vars_prompt:
    - name: trello_api_key
    - name: trello_token

  tasks:
  - name: Install git
    ansible.builtin.yum:
      name: git
      state: latest
    become: true  

  - name: Install python 3.x
    ansible.builtin.yum:
      name: python3
      state: latest
    become: true  
  
  # create /opt/todoapp
  # make the folder read/writeable by ec2-user
  - name: mkdir and chown
    ansible.builtin.file: 
      path: /opt/todoapp
      state: directory
      owner: ec2-user
    become: true

  # retrieve the app 
  - name: clone TODO app into service
    ansible.builtin.git:
      repo: https://github.com/sweavo/devops-course-starter.git
      dest: /opt/todoapp
      single_branch: yes
      version: release/prep
      depth: 1
      force: true
    become: true

  # install poetry 
  - name: install poetry
    ansible.builtin.shell: pip3 install poetry
    become: true

  # install project dependencies 
  - name: get project dependencies
    ansible.builtin.shell: poetry install
    args:
      chdir: /opt/todoapp

  # create a .env file
  - name: create .env file
    ansible.builtin.template:
      src: dot-env.j2
      dest: /opt/todoapp/.env

  # set the app as a service in syssctl
  - name: configure the systemd service
    ansible.builtin.copy:
      src: todoapp.service
      dest: /etc/systemd/system/todoapp.service
    become: true

  # ... and start the app
  - name: start the service
    ansible.builtin.systemd:
      name: todoapp
      daemon_reload: true
      state: restarted
    become: true

  # maybe use ansible vault TODO
  #
