- name: Install to-do app in module4 servers
  hosts: module4
  vars_prompt:
    - name: trello_api_key
    - name: trello_token

  tasks:
  - name: Install git
    ansible.builtin.yum:
      name: git
      state: latest
    become: true  

  - name: Install python 3.x
    ansible.builtin.yum:
      name: python3
      state: latest
    become: true  
  
  - name: create /opt/todoapp with appropriate permissions for ec2-user
    ansible.builtin.file: 
      path: /opt/todoapp
      state: directory
      owner: ec2-user
    become: true

  - name: clone to-do app into folder for service
    ansible.builtin.git:
      repo: https://github.com/sweavo/devops-course-starter.git
      dest: /opt/todoapp
      single_branch: yes
      version: release/prep
      depth: 1
      force: true
    become: true

  - name: install poetry
    ansible.builtin.shell: pip3 install poetry
    become: true

  - name: install project dependencies using poetry
    ansible.builtin.shell: poetry install
    args:
      chdir: /opt/todoapp

  # TODO use ansible vault for secrets
  - name: create .env file from controller's copy
    ansible.builtin.template:
      src: dot-env.j2
      dest: /opt/todoapp/.env

  - name: configure the systemd service
    ansible.builtin.copy:
      src: todoapp.service
      dest: /etc/systemd/system/todoapp.service
    become: true

  - name: start the service
    ansible.builtin.systemd:
      name: todoapp
      daemon_reload: true
      state: restarted
    become: true

