#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --type=bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

set -e
# run pyflakes over the changed files
echo "Info: running pyflakes"
TMPDIR=.tmp_commit
function tidyup { rm -rf $TMPDIR; }
trap tidyup EXIT
mkdir -p $TMPDIR

git diff --cached --name-only --diff-filter=ACM | xargs git checkout-index --prefix=$TMPDIR/
poetry run pyflakes $TMPDIR

