name: Devops Course Todo List Pipeline
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: touch .env
    - run: docker compose build test
    - run: docker compose run test
