name: Devops Course Todo List Pipeline
on: 
  push:
    paths-exclude:
      - 'util/**'
      - 'README.md'
      - 'hooks/**'
      - 'reading/**'
  pull_request:
    branches: 'master'

jobs:
  build:
    name: Unit Tests 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v4
      timeout-minutes: 1
    - name: Touch .env  
      run: touch .env
      timeout-minutes: 1
    - name: Prepare
      run: echo lol # docker compose build test
      timeout-minutes: 1
    - name: Test
      run: echo whut # docker compose run test
      timeout-minutes: 1

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'push' && contains(fromJSON('["refs/heads/master", "refs/heads/module-9-exercise"]'), github.ref) }}
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_KEY }}
      timeout-minutes: 1
    - name: Deploy via makefile
      run: make deploy-docker
      timeout-minutes: 5

