name: Devops Course Todo List Pipeline
on: 
  push:
    paths-exclude:
      - 'util/**'
      - 'README.md'
      - 'Makefile'
      - 'hooks/**'
      - 'reading/**'
  pull_request:
    branches: 'master'

jobs:
  build:
    name: Unit Tests 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v4
      timeout-minutes: 1
    - name: Touch .env  
      run: touch .env
      timeout-minutes: 1
    - name: Prepare
      run: docker compose build test
      timeout-minutes: 1
    - name: Test
      run: docker compose run test
      timeout-minutes: 1

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: echo
      if: ${{ github.event_name == 'push' && contains(fromJSON('["refs/heads/master", "refs/heads/module-9-exercise"]'), github.ref) }}
      env: 
        NAME: ${{ github.event_name }}
        REF: ${{ github.ref }}
      run: |
        echo "event_name: $NAME"
        echo "ref: $REF"
      timeout-minutes: 1

