name: Devops Course Todo List Pipeline
on: [push]

jobs:
  build:
    name: Unit Tests 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
      timeout-minutes: 1
    - name: Touch .env  
      run: touch .env
      timeout-minutes: 1
    - name: Prepare
      run: docker compose build test
      timeout-minutes: 1
    - name: Test
      run: docker compose run test
      timeout-minutes: 1
