name: Devops Course Todo List Pipeline
on: 
  push:
    paths-exclude:
      - 'util/**'
      - 'README.md'
      - 'Makefile'
      - 'hooks/**'
      - 'reading/**'
  pull_request:
    branches: 'master'

jobs:
  build:
    name: Unit Tests 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout
      timeout-minutes: 1
    - name: Touch .env  
      run: touch .env
      timeout-minutes: 1
    - name: Prepare
      run: docker compose build test
      timeout-minutes: 1
    - name: Test
      run: docker compose run test
      timeout-minutes: 1

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: echo
      run: echo hi mum
      timeout-minutes: 1

